Update boredgames.server.yml

diff --git a/.github/workflows/boredgames.server.yml b/.github/workflows/boredgames.server.yml
--- a/.github/workflows/boredgames.server.yml
+++ b/.github/workflows/boredgames.server.yml
@@ -22,10 +22,20 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Check Sentry secret 
+        run: |
+          if [ -z "${{ secrets.BORED_GAMES_SERILOG_DSN }}" ]; then
+            echo "ERROR: Secret is empty or not set!"
+            exit 1
+          fi
+          sed -i "s|__BORED_GAMES_SERILOG_DSN__|${{ secrets.BORED_GAMES_SERILOG_DSN }}|g" .env
+          cat .env | grep SERILOG
           
       - name: Inject Sentry secret into .env file
+        env:
+          SERILOG_DSN: ${{ secrets.BORED_GAMES_SERILOG_DSN }}
         run: |
-          sed -i "s|__BORED_GAMES_SERILOG_DSN__|${{ secrets.BORED_GAMES_SERILOG_DSN }}|g" .env
+          sed -i "s|__BORED_GAMES_SERILOG_DSN__|${SERILOG_DSN}|g" .env
 
       - name: Inject Keycloak client secret in appsettings.Production.json
         run: |
